name: Publish Package

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Restore NuGet Packages
        run: dotnet restore src/VerifactuHuella.sln     
          
      - name: Build solution and generate NuGet package
        run: |  
          cd ./src/
          dotnet pack VerifactuHuella.sln -c Release -o out  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push "**/*.nupkg" --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
